spring.application.name=services-microservices
server.port=8082
server.address=0.0.0.0
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

# DEFAULZONE ES SOLO PARA DOCKER EN LOCAL SE DEBE COMENTAR
eureka.client.service-url.defaultZone=http://services:8761/eureka

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=esthetic_base

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

env.max_file_upload=5
my.property.api.gateway=http://api-gateway:8002